/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type License struct {
	Id                       string   `json:"id,omitempty"`
	CreatedAt                int64    `json:"created_at,omitempty"`
	UpdatedAt                int64    `json:"updated_at,omitempty"`
	Name                     string   `json:"name,omitempty"`
	ActivatedAt              int64    `json:"activated_at,omitempty"`
	LicenseType              string   `json:"license_type,omitempty"`
	LicenseExpiration        int64    `json:"license_expiration,omitempty"`
	LicenseMaxAssets         int64    `json:"license_max_assets,omitempty"`
	LicenseLiveAssetCount    int64    `json:"license_live_asset_count,omitempty"`
	LicenseProjectAssetCount int64    `json:"license_project_asset_count,omitempty"`
	ViaReseller              bool     `json:"via_reseller,omitempty"`
	Phone                    string   `json:"phone,omitempty"`
	AddressStreet            string   `json:"address_street,omitempty"`
	AddressCountry           string   `json:"address_country,omitempty"`
	AddressCity              string   `json:"address_city,omitempty"`
	AddressRegion            string   `json:"address_region,omitempty"`
	AddressPostal            string   `json:"address_postal,omitempty"`
	SubscriptionPeriodStart  int64    `json:"subscription_period_start,omitempty"`
	SubscriptionPeriodEnd    int64    `json:"subscription_period_end,omitempty"`
	SubscriptionCancelAt     int64    `json:"subscription_cancel_at,omitempty"`
	SubscriptionCanceledAt   int64    `json:"subscription_canceled_at,omitempty"`
	Settings                 ModelMap `json:"settings,omitempty"`
	SsoType                  string   `json:"sso_type,omitempty"`
	SsoDomain                string   `json:"sso_domain,omitempty"`
	SsoMode                  string   `json:"sso_mode,omitempty"`
	SsoLoginMessage          string   `json:"sso_login_message,omitempty"`
	SsoLoginIssuerUrl        string   `json:"sso_login_issuer_url,omitempty"`
	SsoLoginLoginUrl         string   `json:"sso_login_login_url,omitempty"`
	SsoLoginLogoutUrl        string   `json:"sso_login_logout_url,omitempty"`
	SsoDefaultRole           string   `json:"sso_default_role,omitempty"`
	Partner                  string   `json:"partner,omitempty"`
}
