/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type User struct {
	Id                    string   `json:"id"`
	ClientId              string   `json:"client_id,omitempty"`
	CreatedAt             int64    `json:"created_at,omitempty"`
	UpdatedAt             int64    `json:"updated_at,omitempty"`
	FirstName             string   `json:"first_name,omitempty"`
	LastName              string   `json:"last_name,omitempty"`
	Email                 string   `json:"email,omitempty"`
	ClientAdmin           bool     `json:"client_admin,omitempty"`
	OrgDefaultRole        string   `json:"org_default_role,omitempty"`
	OrgRoles              ModelMap `json:"org_roles,omitempty"`
	ResetTokenExpiration  int64    `json:"reset_token_expiration,omitempty"`
	InviteTokenExpiration int64    `json:"invite_token_expiration,omitempty"`
	LastLoginIp           string   `json:"last_login_ip,omitempty"`
	LastLoginAt           int64    `json:"last_login_at,omitempty"`
	LastLoginUa           string   `json:"last_login_ua,omitempty"`
	SsoOnly               bool     `json:"sso_only,omitempty"`
	LoginFailures         int64    `json:"login_failures,omitempty"`
}
