/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type GroupMapping struct {
	Id             string `json:"id"`
	GroupId        string `json:"group_id"`
	GroupName      string `json:"group_name,omitempty"`
	SsoAttribute   string `json:"sso_attribute"`
	SsoValue       string `json:"sso_value"`
	Description    string `json:"description,omitempty"`
	CreatedByEmail string `json:"created_by_email,omitempty"`
	CreatedAt      int64  `json:"created_at,omitempty"`
	UpdatedAt      int64  `json:"updated_at,omitempty"`
}
