/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type AzureUsernamePasswordCredentialFields struct {
	ClientId string `json:"client_id"`
	TenantId string `json:"tenant_id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
