/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type AwsCredentialFields struct {
	AccessKey          string `json:"access_key"`
	SecretAccessKey    string `json:"secret_access_key"`
	Regions            string `json:"regions,omitempty"`
	UseCrossAccountOrg string `json:"use_cross_account_org,omitempty"`
	Role               string `json:"role,omitempty"`
}
