/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type AzureClientSecretCredentialFields struct {
	ClientId          string `json:"client_id"`
	ClientSecret      string `json:"client_secret"`
	TenantId          string `json:"tenant_id"`
	MultiSubscription string `json:"multi_subscription,omitempty"`
	SubscriptionId    string `json:"subscription_id,omitempty"`
}
