/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type Agent struct {
	Id             string   `json:"id"`
	ClientId       string   `json:"client_id,omitempty"`
	OrganizationId string   `json:"organization_id,omitempty"`
	CreatedAt      int64    `json:"created_at,omitempty"`
	UpdatedAt      int64    `json:"updated_at,omitempty"`
	HostId         string   `json:"host_id,omitempty"`
	HubId          string   `json:"hub_id,omitempty"`
	Name           string   `json:"name,omitempty"`
	SiteId         string   `json:"site_id,omitempty"`
	LastCheckin    int64    `json:"last_checkin,omitempty"`
	Os             string   `json:"os,omitempty"`
	Arch           string   `json:"arch,omitempty"`
	Version        string   `json:"version,omitempty"`
	ExternalIp     string   `json:"external_ip,omitempty"`
	InternalIp     string   `json:"internal_ip,omitempty"`
	SystemInfo     ModelMap `json:"system_info,omitempty"`
	Connected      bool     `json:"connected,omitempty"`
	Inactive       bool     `json:"inactive,omitempty"`
	DeactivatedAt  int64    `json:"deactivated_at,omitempty"`
}
