/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type SnmPv3CredentialFields struct {
	Username          string `json:"username"`
	Context           string `json:"context,omitempty"`
	AuthProtocol      string `json:"auth-protocol,omitempty"`
	AuthPassphrase    string `json:"auth-passphrase,omitempty"`
	PrivacyProtocol   string `json:"privacy-protocol,omitempty"`
	PrivacyPassphrase string `json:"privacy-passphrase,omitempty"`
}
