/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type AssetsWithCheckpoint struct {
	Since  int64   `json:"since"`
	Assets []Asset `json:"assets"`
}
