/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type Wireless struct {
	Id             string            `json:"id"`
	CreatedAt      int64             `json:"created_at,omitempty"`
	LastSeen       int64             `json:"last_seen,omitempty"`
	OrganizationId string            `json:"organization_id,omitempty"`
	SiteId         string            `json:"site_id,omitempty"`
	LastAgentId    string            `json:"last_agent_id,omitempty"`
	LastTaskId     string            `json:"last_task_id,omitempty"`
	Essid          string            `json:"essid,omitempty"`
	Bssid          string            `json:"bssid,omitempty"`
	Type_          string            `json:"type,omitempty"`
	Authentication string            `json:"authentication,omitempty"`
	Encryption     string            `json:"encryption,omitempty"`
	Signal         int32             `json:"signal,omitempty"`
	Channels       string            `json:"channels,omitempty"`
	Interface_     string            `json:"interface,omitempty"`
	Vendor         string            `json:"vendor,omitempty"`
	Family         string            `json:"family,omitempty"`
	Data           map[string]string `json:"data,omitempty"`
	OrgName        string            `json:"org_name,omitempty"`
	SiteName       string            `json:"site_name,omitempty"`
	AgentName      string            `json:"agent_name,omitempty"`
}
