/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type GroupPut struct {
	Id             string   `json:"id,omitempty"`
	Description    string   `json:"description,omitempty"`
	Name           string   `json:"name,omitempty"`
	ExpiresAt      int64    `json:"expires_at,omitempty"`
	OrgDefaultRole string   `json:"org_default_role,omitempty"`
	OrgRoles       ModelMap `json:"org_roles,omitempty"`
}
