/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type ScanOptions struct {
	Targets              string `json:"targets"`
	Excludes             string `json:"excludes,omitempty"`
	ScanName             string `json:"scan-name,omitempty"`
	ScanDescription      string `json:"scan-description,omitempty"`
	ScanFrequency        string `json:"scan-frequency,omitempty"`
	ScanStart            string `json:"scan-start,omitempty"`
	ScanTags             string `json:"scan-tags,omitempty"`
	ScanGracePeriod      string `json:"scan-grace-period,omitempty"`
	Agent                string `json:"agent,omitempty"`
	Rate                 string `json:"rate,omitempty"`
	MaxHostRate          string `json:"max-host-rate,omitempty"`
	Passes               string `json:"passes,omitempty"`
	MaxAttempts          string `json:"max-attempts,omitempty"`
	MaxSockets           string `json:"max-sockets,omitempty"`
	MaxGroupSize         string `json:"max-group-size,omitempty"`
	MaxTtl               string `json:"max-ttl,omitempty"`
	TcpPorts             string `json:"tcp-ports,omitempty"`
	TcpExcludes          string `json:"tcp-excludes,omitempty"`
	Screenshots          string `json:"screenshots,omitempty"`
	Nameservers          string `json:"nameservers,omitempty"`
	SubnetPing           string `json:"subnet-ping,omitempty"`
	SubnetPingNetSize    string `json:"subnet-ping-net-size,omitempty"`
	SubnetPingSampleRate string `json:"subnet-ping-sample-rate,omitempty"`
	HostPing             string `json:"host-ping,omitempty"`
	// Optional probe list, otherwise all probes are used
	Probes string `json:"probes,omitempty"`
}
