/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type VMwareCredentialFields struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	Insecure    string `json:"insecure,omitempty"`
	Thumbprints string `json:"thumbprints,omitempty"`
}
