/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type Asset struct {
	Id                    string                       `json:"id"`
	CreatedAt             int64                        `json:"created_at,omitempty"`
	UpdatedAt             int64                        `json:"updated_at,omitempty"`
	OrganizationId        string                       `json:"organization_id,omitempty"`
	SiteId                string                       `json:"site_id,omitempty"`
	Alive                 bool                         `json:"alive,omitempty"`
	FirstSeen             int64                        `json:"first_seen,omitempty"`
	LastSeen              int64                        `json:"last_seen,omitempty"`
	DetectedBy            string                       `json:"detected_by,omitempty"`
	Type_                 string                       `json:"type,omitempty"`
	Os                    string                       `json:"os,omitempty"`
	OsVersion             string                       `json:"os_version,omitempty"`
	Hw                    string                       `json:"hw,omitempty"`
	Addresses             []string                     `json:"addresses,omitempty"`
	AddressesExtra        []string                     `json:"addresses_extra,omitempty"`
	Macs                  []string                     `json:"macs,omitempty"`
	MacVendors            []string                     `json:"mac_vendors,omitempty"`
	Names                 []string                     `json:"names,omitempty"`
	Domains               []string                     `json:"domains,omitempty"`
	ServiceCount          int64                        `json:"service_count,omitempty"`
	ServiceCountTcp       int64                        `json:"service_count_tcp,omitempty"`
	ServiceCountUdp       int64                        `json:"service_count_udp,omitempty"`
	ServiceCountArp       int64                        `json:"service_count_arp,omitempty"`
	ServiceCountIcmp      int64                        `json:"service_count_icmp,omitempty"`
	LowestTtl             int64                        `json:"lowest_ttl,omitempty"`
	LowestRtt             int64                        `json:"lowest_rtt,omitempty"`
	LastAgentId           string                       `json:"last_agent_id,omitempty"`
	LastTaskId            string                       `json:"last_task_id,omitempty"`
	NewestMac             string                       `json:"newest_mac,omitempty"`
	NewestMacVendor       string                       `json:"newest_mac_vendor,omitempty"`
	NewestMacAge          int64                        `json:"newest_mac_age,omitempty"`
	Comments              string                       `json:"comments,omitempty"`
	ServicePortsTcp       []string                     `json:"service_ports_tcp,omitempty"`
	ServicePortsUdp       []string                     `json:"service_ports_udp,omitempty"`
	ServicePortsProtocols []string                     `json:"service_ports_protocols,omitempty"`
	ServicePortsProducts  []string                     `json:"service_ports_products,omitempty"`
	OrgName               string                       `json:"org_name,omitempty"`
	SiteName              string                       `json:"site_name,omitempty"`
	AgentName             string                       `json:"agent_name,omitempty"`
	Tags                  map[string]string            `json:"tags,omitempty"`
	Services              map[string]map[string]string `json:"services,omitempty"`
	Rtts                  ModelMap                     `json:"rtts,omitempty"`
	Credentials           map[string]map[string]bool   `json:"credentials,omitempty"`
	Attributes            map[string]string            `json:"attributes,omitempty"`
}
