/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

// A component ID and version
type ComponentVersion struct {
	Id      string `json:"id"`
	Version string `json:"version"`
}
