/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type Credential struct {
	Id       string `json:"id"`
	ClientId string `json:"client_id,omitempty"`
	Name     string `json:"name,omitempty"`
	// The service the credentials are for.
	Type_          string   `json:"type,omitempty"`
	CreatedAt      int64    `json:"created_at,omitempty"`
	CreatedById    string   `json:"created_by_id,omitempty"`
	CreatedByEmail string   `json:"created_by_email,omitempty"`
	Acl            ModelMap `json:"acl,omitempty"`
	Global         bool     `json:"global,omitempty"`
	Cidrs          []string `json:"cidrs,omitempty"`
	LastUsedAt     int64    `json:"last_used_at,omitempty"`
	LastUsedById   string   `json:"last_used_by_id,omitempty"`
}
