/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type Event struct {
	Id             string   `json:"id,omitempty"`
	CreatedAt      int64    `json:"created_at,omitempty"`
	ClientId       string   `json:"client_id,omitempty"`
	OrganizationId string   `json:"organization_id,omitempty"`
	SiteId         string   `json:"site_id,omitempty"`
	Action         string   `json:"action,omitempty"`
	SourceId       string   `json:"source_id,omitempty"`
	SourceName     string   `json:"source_name,omitempty"`
	SourceType     string   `json:"source_type,omitempty"`
	TargetId       string   `json:"target_id,omitempty"`
	TargetName     string   `json:"target_name,omitempty"`
	TargetType     string   `json:"target_type,omitempty"`
	Success        bool     `json:"success,omitempty"`
	Details        ModelMap `json:"details,omitempty"`
	State          string   `json:"state,omitempty"`
	ProcessorId    string   `json:"processor_id,omitempty"`
	ProcessedAt    int64    `json:"processed_at,omitempty"`
}
