/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type CredentialOptions struct {
	Name   string            `json:"name,omitempty"`
	Type_  string            `json:"type,omitempty"`
	Acl    ModelMap          `json:"acl,omitempty"`
	Global bool              `json:"global,omitempty"`
	Cidrs  string            `json:"cidrs,omitempty"`
	Secret *CredentialFields `json:"secret,omitempty"`
}
