/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type OrgOptions struct {
	Name                    string  `json:"name,omitempty"`
	Description             string  `json:"description,omitempty"`
	ExportToken             string  `json:"export_token,omitempty"`
	Project                 string  `json:"project,omitempty"`
	ParentId                string  `json:"parent_id,omitempty"`
	ExpirationAssetsStale   float64 `json:"expiration_assets_stale,omitempty"`
	ExpirationAssetsOffline float64 `json:"expiration_assets_offline,omitempty"`
	ExpirationScans         float64 `json:"expiration_scans,omitempty"`
}
