/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type CrowdstrikeCredentialFields struct {
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	ApiUrl       string `json:"api_url"`
}
