/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type Site struct {
	Id          string   `json:"id"`
	CreatedAt   int64    `json:"created_at,omitempty"`
	UpdatedAt   int64    `json:"updated_at,omitempty"`
	Permanent   bool     `json:"permanent,omitempty"`
	Name        string   `json:"name"`
	Description string   `json:"description,omitempty"`
	Scope       string   `json:"scope,omitempty"`
	Excludes    string   `json:"excludes,omitempty"`
	Subnets     ModelMap `json:"subnets,omitempty"`
}
