/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type ApiKey struct {
	Id             string `json:"id"`
	ClientId       string `json:"client_id,omitempty"`
	OrganizationId string `json:"organization_id,omitempty"`
	CreatedAt      int64  `json:"created_at,omitempty"`
	CreatedBy      string `json:"created_by,omitempty"`
	Comment        string `json:"comment,omitempty"`
	LastUsedAt     int64  `json:"last_used_at,omitempty"`
	LastUsedIp     string `json:"last_used_ip,omitempty"`
	LastUsedUa     string `json:"last_used_ua,omitempty"`
	Counter        int64  `json:"counter,omitempty"`
	UsageToday     int64  `json:"usage_today,omitempty"`
	UsageLimit     int64  `json:"usage_limit,omitempty"`
	Token          string `json:"token,omitempty"`
	Inactive       bool   `json:"inactive,omitempty"`
	Type_          string `json:"type,omitempty"`
}
