/*
 * runZero API
 *
 * runZero API
 *
 * API version: 3.0.0
 * Contact: support@runzero.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package runzeroapi

type UserOptions struct {
	FirstName      string   `json:"first_name,omitempty"`
	LastName       string   `json:"last_name,omitempty"`
	Email          string   `json:"email,omitempty"`
	ClientAdmin    bool     `json:"client_admin,omitempty"`
	OrgDefaultRole string   `json:"org_default_role,omitempty"`
	OrgRoles       ModelMap `json:"org_roles,omitempty"`
}
